# -*- coding: utf-8-unix -*-
#+TITLE: Playground to learn and understand Jupyter Notebooks

** IP[y]: IPython Interactive Computing

Recently I started to learn Python-Tricks (in German)
and remembered IPython and its Notebook facility 
and check if I can use it to make notes on Python-Tricks.

In meantime all python language-agnostic components 
are moved from IPython to Jupyter.

"IPython 3.x was the last monolithic release of IPython, 
containing the notebook server, qtconsole, etc. 
As of IPython 4.0, the language-agnostic parts of the project: 
the notebook format, message protocol, qtconsole, notebook web application, etc. 
have moved to new projects under the name [[https://jupyter.org/][Jupyter]]. 
IPython itself is focused on interactive Python, 
part of which is providing a Python kernel for Jupyter."

You can get good old IPython when executing a ~jupyter console~
instead of a ~jupyter notebook~ ;-).

** Learning about Jupyter Notebook
- This blog entry refers to a text book:
  https://blog.jupyter.org/teaching-and-learning-with-jupyter-c1d965f7b93a
- A text book: 
  https://www.packtpub.com/big-data-and-business-intelligence/learning-jupyter
- And the [[https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks][A gallery of interesting Jupyter Notebooks]] 
  which are to be displayed by [[https://nbviewer.jupyter.org/][NBViewer]].
- The Notebook Help displayed by nbviewer:
  https://nbviewer.jupyter.org/github/ipython/ipython/blob/3.x/examples/Notebook/Index.ipynb
- [[http://jupyterlab.readthedocs.io/en/stable/][JupyterLab]] is the next-generation user interface 
  for [[https://jupyter.org/][Project Jupyter]] offering all the familiar building blocks 
  of the classic Jupyter Notebook in a flexible and powerful user interface. 
  JupyterLab will eventually replace the classic Jupyter Notebook.
- [[https://mybinder.readthedocs.io/en/latest/][Binder]] is the notbook execution environment,
  which not only supports executing Jupyter Notebooks powered by it's core kernels 
  for programming languages such as Ju(Julia)-pyt(Python)-er(R) but also for R(ust :).
  See binder's documentation headline [[https://mybinder.readthedocs.io/en/latest/howto/languages.html?highlight=multi#using-multiple-languages-at-once][Using multiple languages at once]].
  - Python :: your environment will have Python (and specified dependencies) installed 
    when you use one of the following configuration files:
    - =requirements.txt=; utilized by ~pip~
    - =environment.yml=; utilized by ~conda~
  - R :: you must specify a version of R in a =runtime.txt= file. 
  - Julia :: include a configuration file called =Project.toml=. 

** Install Jupyter Notebook with Pipenv

[[https://pipenv.readthedocs.io/en/latest/][Pipenv]]: Python Dev Workflow for Humans

Pipenv is a tool that aims to bring the best of all packaging worlds 
(bundler, composer, npm, cargo, yarn, etc.) to the Python world. 
Windows is a first-class citizen, in our world.

It automatically creates and manages a virtualenv for your projects, 
as well as adds/removes packages from your Pipfile as you install/uninstall packages. 
It also generates the ever-important Pipfile.lock, 
which is used to produce deterministic builds.

Importing from requirements.txt

If you only have a requirements.txt file available when running pipenv install, 
pipenv will automatically import the contents of this file and create a Pipfile for you.

You can also specify =$ pipenv install -r path/to/requirements.txt= to import a requirements file.

Pipenv Workflow
- Clone / create project repository:
  =$ cd play-jupyter=
- Install from Pipfile, if there is one 
  or will create a Pipfile if one doesn’t exist 
  (or pipenv will automatically import the contents of requirements.txt):
  =pipenv install --three=
- Or, add a package to your new project:
  =$ pipenv install <package>=
- Next, activate the Pipenv shell:
  =$ pipenv shell=

#+BEGIN_EXAMPLE
  pipenv install --three
  pipenv run pip list
#+END_EXAMPLE

Let's see how PIP 

#+BEGIN_SRC shell :tangle no
  pipenv --where
  pipenv --venv
  pipenv --py
#+END_SRC 

** Run a Jupyter Notebook with Pipenv

Run a Jupyter notebook and open displayed URL in browser 
(does not open automatically as we are running cygwin). 

#+BEGIN_EXAMPLE
  pipenv run jupyter-notebook
#+END_EXAMPLE

As long as shell is controlled by Emacs you may open 
the displayed URL by mark the URL and type M+x '[[help:browse-url][browse-url]]'.

** Install Jupyter (Qt)Console with Pipenv

Even though jupyter-console seems to be installed with jupyter,
I could neither start ~jupyter console~ nor ~jupyter qtconsole~:
#+BEGIN_EXAMPLE
[tilo@holm play-jupyter]$ 
[tilo@holm play-jupyter]$ pipenv run jupyter console
Jupyter console 6.4.0

Python 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.
Traceback (most recent call last):
  File "/home/tilo/.local/share/virtualenvs/play-jupyter-8vMFQbMi/bin/jupyter-console", line 8, in <module>
    sys.exit(main())
...
    File "/home/tilo/.local/share/virtualenvs/play-jupyter-8vMFQbMi/lib/python3.10/site-packages/jupyter_console/ptshell.py", line 664, in mainloop
    main_task = asyncio.wait(tasks, loop=loop, return_when=asyncio.FIRST_COMPLETED)
TypeError: wait() got an unexpected keyword argument 'loop'
sys:1: RuntimeWarning: coroutine 'ZMQTerminalInteractiveShell.interact' was never awaited
[tilo@holm play-jupyter]$ 
#+END_EXAMPLE

Even not after installed ~qtconsole~:
#+BEGIN_EXAMPLE
  [tilo@holm play-jupyter]$ 
  [tilo@holm play-jupyter]$ pipenv install qtconsole
  Installing qtconsole...
  Adding qtconsole to Pipfile's [packages]...
  ✔ Installation Succeeded 
  Pipfile.lock (5509dc) out of date, updating to (3b5bc9)...
  Locking [dev-packages] dependencies...
  Locking [packages] dependencies...
  Building requirements...
  Resolving dependencies...
  ✔ Success! 
  Updated Pipfile.lock (3b5bc9)!
  Installing dependencies from Pipfile.lock (3b5bc9)...
    🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
  [tilo@holm play-jupyter]$ 
  [tilo@holm play-jupyter]$ 
  [tilo@holm play-jupyter]$ pipenv run jupyter qtconsole
  Traceback (most recent call last):
    File "/home/tilo/.local/share/virtualenvs/play-jupyter-8vMFQbMi/bin/jupyter-qtconsole", line 5, in <module>
      from qtconsole.qtconsoleapp import main
    File "/home/tilo/.local/share/virtualenvs/play-jupyter-8vMFQbMi/lib/python3.10/site-packages/qtconsole/qtconsoleapp.py", line 61, in <module>
      from qtpy import QtCore, QtGui, QtWidgets, QT_VERSION
    File "/home/tilo/.local/share/virtualenvs/play-jupyter-8vMFQbMi/lib/python3.10/site-packages/qtpy/QtCore.py", line 42, in <module>
      from PyQt5.QtCore import *
  ModuleNotFoundError: No module named 'PyQt5'
  [tilo@holm play-jupyter]$ 
#+END_EXAMPLE

It has been required to install ~PyQt5~ manually.
#+BEGIN_EXAMPLE
  pipenv install PyQt5
#+END_EXAMPLE

** Run a Jupyter QtConsole with Pipenv

Run a Jupyter QtConsole opens a Qt-Terminal window with
good old IPython :-), or may be not the same; see my by-the-way below
on editing cells, not only when a line has a double colon.

#+BEGIN_EXAMPLE
  pipenv run jupyter qtconsole
#+END_EXAMPLE

By-The-Way: it took some hours to find the right keyboard combination
to start editing a ~cell~ rather than a ~line~
(similar to "magic" ~%<line>~ or ~%%<cell>~).
I was not able to edit more then one line when the python code has no
~:~ in a =ipython= installation of my system.

Only after I installed ~jupyter qtconsole~ I found =CTRL+ENTER= to
get start editing the next line instead of evaluate the current line.

#+BEGIN_EXAMPLE
  In [44]: cwd = !pwd          <-- TILO: Ctrl+Enter
      ...: !ls -la $cwd        <-- TILO: Enter
  ls: Zugriff auf '[/home/tilo/Projects/play-jupyter]' nicht möglich: Datei oder Verzeichnis nicht gefunden

  In [45]: cwd?
  Type:        SList
  String form: ['/home/tilo/Projects/play-jupyter']
  Length:      1
  File:        ~/.local/share/virtualenvs/play-jupyter-8vMFQbMi/lib/python3.10/site-packages/IPython/utils/text.py
  Docstring:  
  List derivative with a special access attributes.

  These are normal lists, but with the special attributes:

  ,* .l (or .list) : value as list (the list itself).
  ,* .n (or .nlstr): value as a string, joined on newlines.
  ,* .s (or .spstr): value as a string, joined on spaces.
  ,* .p (or .paths): list of path objects (requires path.py package)

  Any values which require transformations are computed only once and
  cached.

  In [46]: cwd = !pwd
      ...: !ls -la $cwd.spstr
  insgesamt 240
  drwxr-xr-x  4 tilo tilo  4096 29. Jan 16:41  .
  drwxr-xr-x 12 tilo tilo  4096 14. Jan 17:02  ..
  drwxr-xr-x  8 tilo tilo  4096 29. Jan 16:38  .git
  -rw-r--r--  1 tilo tilo  1223 12. Dez 2020   .gitignore
  drwxr-xr-x  2 tilo tilo  4096  4. Jan 2021   .ipynb_checkpoints
  -rw-r--r--  1 tilo tilo 96119 23. Jan 20:52  julia_notes.ipynb
  -rw-r--r--  1 tilo tilo   211 29. Jan 16:15  Pipfile
  -rw-r--r--  1 tilo tilo 49702 29. Jan 16:15  Pipfile.lock
  -rw-r--r--  1 tilo tilo  4995 23. Jan 20:17  python3_notes.ipynb
  -rw-r--r--  1 tilo tilo  8109 29. Jan 07:50  python_tricks.ipynb
  -rw-r--r--  1 tilo tilo 20372 29. Jan 16:41 '#README.org#'
  lrwxrwxrwx  1 tilo tilo    25 29. Jan 16:40  .#README.org -> tilo@holm.4452:1643453754
  -rw-r--r--  1 tilo tilo 20323 29. Jan 16:38  README.org
  -rw-r--r--  1 tilo tilo   489 12. Dez 2020   requirements.txt
  -rw-r--r--  1 tilo tilo  2187  4. Jan 2021   rust_notes.ipynb
  -rw-r--r--  1 tilo tilo    27 12. Dez 2020   textfile.txt

#+END_EXAMPLE

Interesting to learn more on that IPython type ~SList~.
First is says it is like a normal list but I cannot deference it's item.

#+BEGIN_EXAMPLE
  In [58]: cwd = !pwd
      ...: !ls -la $cwd[0]
  ls: Zugriff auf '[/home/tilo/Projects/play-jupyter][0]' nicht möglich: Datei oder Verzeichnis nicht gefunden

#+END_EXAMPLE

The [[https://ipython.readthedocs.io/en/stable/interactive/reference.html#system-shell-access][IPython reference]] helps in chapter "Interactive use" when it talks
about "System shell access". 

-----

IPython also allows you to expand the value of python variables when
making system calls.

Wrap variables or expressions in ~{~braces~}~:
#+BEGIN_EXAMPLE
  In [60]: pyvar = 'Hello Jupyter'
      ...: !echo "A python variable: {pyvar}"
  A python variable: Hello Jupyter

  In [61]: import math
      ...: x = 8
      ...: !echo {math.factorial(x)}
  40320

#+END_EXAMPlE

For simple cases, you can alternatively prepend ~$~ to a variable name:

#+BEGIN_EXAMPLE
  In [64]: import sys
      ...: !echo $sys.argv
  [/home/tilo/.local/share/virtualenvs/play-jupyter-8vMFQbMi/lib/python3.10/site-packages/ipykernel_launcher.py, -f, /home/tilo/.local/share/jupyter/runtime/kernel-6328.json]

  In [65]: !echo "A system variable: $$HOME" # Use $$ for literal $
  A system variable: /home/tilo

#+END_EXAMPlE

-----

OK, got it. Here were with my own example:
#+BEGIN_EXAMPLE
  In [56]: dir_list = ["..","."]
      ...: !ls -l {dir_list[1]}
  insgesamt 204
  -rw-r--r-- 1 tilo tilo 96119 23. Jan 20:52 julia_notes.ipynb
  -rw-r--r-- 1 tilo tilo   211 29. Jan 16:15 Pipfile
  -rw-r--r-- 1 tilo tilo 49702 29. Jan 16:15 Pipfile.lock
  -rw-r--r-- 1 tilo tilo  4995 23. Jan 20:17 python3_notes.ipynb
  -rw-r--r-- 1 tilo tilo  8109 29. Jan 07:50 python_tricks.ipynb
  -rw-r--r-- 1 tilo tilo 22539 29. Jan 17:04 README.org
  -rw-r--r-- 1 tilo tilo   489 12. Dez 2020  requirements.txt
  -rw-r--r-- 1 tilo tilo  2187  4. Jan 2021  rust_notes.ipynb
  -rw-r--r-- 1 tilo tilo    27 12. Dez 2020  textfile.txt

#+END_EXAMPLE

** Jupyter and Emacs Org Mode

There are two emacs packages worth visiting:
- EIN :: "The Emacs IPython Notebook (EIN) package provides a Jupyter
  Notebook client and integrated REPL (like SLIME) in Emacs."
  Documentation: http://millejoh.github.io/emacs-ipython-notebook/
- emacs-jupyter :: "Provides REPL and ~org-mode~ source block
  frontends to Jupyter kernels."

** Off-topic: Install Docker on Manjaro, required by jupyter-repo2docker

It hasn't been sufficient to ~pamac install docker~.
Package ~docker~ together with dependencies like ~containerd~ had been installed
but ~docker.service~ did neither run nor had been started during start-up.
[[LinuxConfig.org][https://linuxconfig.org/manjaro-linux-docker-installation]] 
had an answer for me:
- with a ~sudoer~ account execute following commands:
  - =sudo systemctl start docker.service=
  - =sudo systemctl enable docker.service=
- and with a ~sudoer~ account make users planned to execute ~docker~
  a member of group ~docker~: =sudo usermod --append --group docker tilo=,
  and relogin.

** Off-topic: Learning GIT by doing "[[https://alexwlchan.net/a-plumbers-guide-to-git/][A Plumber’s Guide to Git]]" and "man git-push"

Note: this would be better belong to repository =play-git=,
but I wasn't not able to reproduce the same situation having two
different root-commits create by ~GitHub~ remotely, and locally by ~git
init~. And but the example hashes of ~commit~ and ~tree~ objects
belong to this repo.

I initialized the local git repository and did 2 commits
?and created a repository on Adtran's github and did 1 commit.
After I tried to synchronize my local with remote repository 
I ended up in an fatal error:

#+BEGIN_EXAMPLE
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ git pull adtran 
  warning: keine gemeinsamen Commits
  remote: Enumerating objects: 3, done.        
  remote: Counting objects: 100% (3/3), done.        
  remote: Compressing objects: 100% (2/2), done.        
  remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0        
  Entpacke Objekte: 100% (3/3), Fertig.
  Von github.adtran.com:twirkner/play-jupyter
   ,* [neuer Branch]    master     -> adtran/master
  Sie führten "pull" von Remote-Repository 'adtran' aus, ohne einen
  Branch anzugeben. Da das nicht das konfigurierte Standard-Remote-
  Repository für den aktuellen Branch ist, müssen Sie einen Branch auf
  der Befehlszeile angeben.
  56S8TZ1[play-jupyter]$ git pull adtran master
  Von github.adtran.com:twirkner/play-jupyter
   ,* branch            master     -> FETCH_HEAD
  fatal: Verweigere den Merge von nicht zusammenhängenden Historien.
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ git push adtran master
  To github.adtran.com:twirkner/play-jupyter.git
   ! [rejected]        master -> master (non-fast-forward)
  error: Fehler beim Versenden einiger Referenzen nach 'git@github.adtran.com:twirkner/play-jupyter.git'
  Hinweis: Aktualisierungen wurden zurückgewiesen, weil die Spitze Ihres aktuellen
  Hinweis: Branches hinter seinem externen Gegenstück zurückgefallen ist. Führen Sie
  Hinweis: die externen Änderungen zusammen (z. B. 'git pull ...') bevor Sie "push"
  Hinweis: erneut ausführen.
  Hinweis: Siehe auch die Sektion 'Note about fast-forwards' in 'git push --help'
  Hinweis: für weitere Details.
  56S8TZ1[play-jupyter]$ 
#+END_EXAMPLE

My two ~git init~ calls - one on github - lead to two root commits
being ~6a0fc90~ as well as ~ec32c54~:
- refs
  - =$ cat .git/refs/heads/master= 
    c49dbd12c30126fd711390f1b8dd8ee712a78b34
  - =$ cat .git/refs/remotes/adtran/master=
    ec32c5429d67e71de38cebcd720f23e6aae199e8
- commit objects
  - (is a root commit, has not parent) =$ git cat-file -p 6a0fc90cf9c5152cfb452a42f9bb3efc9dae9176=
    - tree c7bfd0fc492f13509954a5018e701ccf4783e90e
      - =$ git cat-file -p c7bfd0fc492f13509954a5018e701ccf4783e90e=
        - tree objects
          #+BEGIN_EXAMPLE
            100644 blob 561b881505065ada9f3124bb4268232bcf336c19	python3_notes.ipynb
          #+END_EXAMPLE
    - author Tilo Wirkner <tilo.wirkner@adtran.com> 1553258993 +0100
    - committer Tilo Wirkner <tilo.wirkner@adtran.com> 1553258993 +0100
    - log message 
      #+BEGIN_EXAMPLE
        Initial commit of new project
        
        Playground to learn and understand Jupyter Notebooks
      #+END_EXAMPLE
  - =$ git cat-file -p c49dbd12c30126fd711390f1b8dd8ee712a78b34=
    - tree d449f244dae6c29f26704dfb6098e3d4ea6e3112
      - =$ git cat-file -p d449f244dae6c29f26704dfb6098e3d4ea6e3112=
        - tree objects
          #+BEGIN_EXAMPLE
            100644 blob 894a44cc066a027465cd26d634948d56d13af9af	.gitignore
            100644 blob 2530266a36a8b2e18003b65797cee0f9c4bd60bb	Pipfile
            100644 blob 55eb3e5fdeeb609a0848da7975b26ac1a86a6bd7	Pipfile.lock
            100644 blob ac93b4b55546e714ab1feb414e4e14d5bb2e488a	README.org
            100644 blob 561b881505065ada9f3124bb4268232bcf336c19	python3_notes.ipynb
            100644 blob cee5e58443d3bd60769a48d731921ed50adb581c	python_tricks.ipynb
            100644 blob 3224ceb843bc7c13269b27d228cfb94aa978a70c	requirements.txt
            100644 blob 7ecbe2956dc100d3b29bcabe84f6702ae55fcd72	textfile.txt
          #+END_EXAMPLE
    - parent 6a0fc90cf9c5152cfb452a42f9bb3efc9dae9176
    - author Tilo Wirkner <tilo.wirkner@adtran.com> 1553259039 +0100
    - committer Tilo Wirkner <tilo.wirkner@adtran.com> 1553259039 +0100
    - log message 
      #+BEGIN_EXAMPLE
        Supplement to the initial commit - missed to mark all files :-O
      #+END_EXAMPLE
  - (is a root commit, has not parent) =$ git cat-file -p ec32c5429d67e71de38cebcd720f23e6aae199e8=
    - tree 90a01769a94b92239d70f8d1fe46eea48d3aa446
      - =$ git cat-file -p 90a01769a94b92239d70f8d1fe46eea48d3aa446=
        - tree objects
          #+BEGIN_EXAMPLE
            100644 blob 894a44cc066a027465cd26d634948d56d13af9af	.gitignore
          #+END_EXAMPLE
    - author TILO WIRKNER <TILO.WIRKNER@adtran.com> 1553257717 +0100
    - committer GitHub Enterprise <github-noreply@adtran.com> 1553257717 +0100
    - log message 
      #+BEGIN_EXAMPLE
        Initial commit
      #+END_EXAMPLE

The issue is explained in "NOTE ABOUT FAST-FORWARDS" 
in manual page of [[https://manpages.debian.org/bullseye/git-man/git-push.1.en.html][git-push]].

#+BEGIN_EXAMPLE
  In contrast, a non-fast-forward update will lose history. For example, suppose you and somebody else
  started at the same commit X, and you built a history leading to commit B while the other person built a
  history leading to commit A. The history looks like this:

            B
           /
       ---X---A

  Further suppose that the other person already pushed changes leading to A back to the original repository
  from which you two obtained the original commit X.

  The push done by the other person updated the branch that used to point at commit X to point at commit A.
  It is a fast-forward.

  But if you try to push, you will attempt to update the branch (that now points at A) with commit B. This
  does not fast-forward. If you did so, the changes introduced by commit A will be lost, because everybody
  will now start building on top of B.

  The command by default does not allow an update that is not a fast-forward to prevent such loss of
  history.

  If you do not want to lose your work (history from X to B) or the work by the other person (history from
  X to A), you would need to first fetch the history from the repository, create a history that contains
  changes done by both parties, and push the result back.

  You can perform "git pull", resolve potential conflicts, and "git push" the result. A "git pull" will
  create a merge commit C between commits A and B.

            B---C
           /   /
       ---X---A

  Updating A with the resulting merge commit will fast-forward and your push will be accepted.

  Alternatively, you can rebase your change between X and B on top of A, with "git pull --rebase", and push
  the result back. The rebase will create a new commit D that builds the change between X and B on top of
  A.

            B   D
           /   /
       ---X---A

  Again, updating A with this commit will fast-forward and your push will be accepted.
#+END_EXAMPLE

Ok, let's go ... Upps

#+BEGIN_EXAMPLE
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ git pull --rebase adtran master
  error: Pull mit Rebase nicht möglich: Sie haben Änderungen, die nicht zum Commit vorgemerkt sind.
  error: Bitte committen Sie die Änderungen oder benutzen Sie "stash".
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ git status
  Auf Branch master
  Änderungen, die nicht zum Commit vorgemerkt sind:
    (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
    (benutzen Sie "git checkout -- <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)

          geändert:       README.org

  keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")
  56S8TZ1[play-jupyter]$ 
#+END_EXAMPLE

I changed the file I writing in ... let's stash it away and do the rebase. 

#+BEGIN_EXAMPLE
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ git stash push
  Saved working directory and index state WIP on master: c49dbd1 Supplement to the initial commit - missed to mark all files :-O
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$git pull --rebase adtran master
  Von github.adtran.com:twirkner/play-jupyter
   ,* branch            master     -> FETCH_HEAD
  First, rewinding head to replay your work on top of it...
  Wende an: Initial commit of new project
  Wende an: Supplement to the initial commit - missed to mark all files :-O
  Verwende Informationen aus der Staging-Area, um ein Basisverzeichnis nachzustellen ...
  .git/rebase-apply/patch:537: trailing whitespace.
  and remembered IPython and its Notebook facility 
  .git/rebase-apply/patch:540: trailing whitespace.
  In meantime all python language-agnostic components 
  .git/rebase-apply/patch:543: trailing whitespace.
  "IPython 3.x was the last monolithic release of IPython, 
  .git/rebase-apply/patch:544: trailing whitespace.
  containing the notebook server, qtconsole, etc. 
  .git/rebase-apply/patch:545: trailing whitespace.
  As of IPython 4.0, the language-agnostic parts of the project: 
  warning: unterdrückte 18 Whitespace-Fehler
  warning: 23 Zeilen fügen Whitespace-Fehler hinzu.
  Falle zurück zum Patchen der Basis und zum 3-Wege-Merge ...
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ git status
  Auf Branch master
  nichts zu committen, Arbeitsverzeichnis unverändert
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ git push adtran master
  Zähle Objekte: 11, Fertig.
  Delta compression using up to 4 threads.
  Komprimiere Objekte: 100% (10/10), Fertig.
  Schreibe Objekte: 100% (11/11), 10.99 KiB | 2.75 MiB/s, Fertig.
  Total 11 (delta 0), reused 0 (delta 0)
  To github.adtran.com:twirkner/play-jupyter.git
     ec32c54..c88be29  master -> master
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ git stash pop
  Auf Branch master
  Änderungen, die nicht zum Commit vorgemerkt sind:
    (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
    (benutzen Sie "git checkout -- <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)

          geändert:       README.org

  keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")
  Dropped refs/stash@{0} (8f8e986c4285eb21374246e4327c2a5ccbef91fc)
  56S8TZ1[play-jupyter]$ 
#+END_EXAMPLE

OK, we are back on track :-).

*** Post Scriptum for Learning GIT by doing "[[https://alexwlchan.net/a-plumbers-guide-to-git/][A Plumber’s Guide to Git]]" 

The plumber's guide did not explain why I get different hash values 
when ~git~ creates SHA1 value and when ~sha1sum~ creates SHA1.

#+BEGIN_EXAMPLE
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ git hash-object python3_notes.ipynb 
  561b881505065ada9f3124bb4268232bcf336c19
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ sha1sum.exe python3_notes.ipynb 
  edcbcd188a8e3bd1e18e125d79670fbbcf02e1bf *python3_notes.ipynb
  56S8TZ1[play-jupyter]$ 
#+END_EXAMPLE

I found answer in this stackoverflow thread:
[[https://stackoverflow.com/questions/5290444/why-does-git-hash-object-return-a-different-hash-than-openssl-sha1#5290484][Why does git hash-object return a different hash than openssl sha1?]]

You see a difference because git hash-object doesn't just take a hash of the bytes in the file - 
it prepends the string "blob " followed by the file size and a NUL to the file's contents before hashing. 
There are more details in this other answer on Stack Overflow:
[[https://stackoverflow.com/questions/552659/how-to-assign-a-git-sha1s-to-a-file-without-git/552725#552725][How to assign a Git SHA1's to a file without Git?]]

Let's verify with help of ~stat~ to get size of the file in question.

#+BEGIN_EXAMPLE
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ stat --format %s python3_notes.ipynb 
  4634
  56S8TZ1[play-jupyter]$ 
  56S8TZ1[play-jupyter]$ printf 'blob 4634\0' | cat - python3_notes.ipynb | sha1sum.exe -
  561b881505065ada9f3124bb4268232bcf336c19 *-
  56S8TZ1[play-jupyter]$ 
#+END_EXAMPLE

So ~git~ prepends a type/length field to the data it has to hash.

Finally, let's check where this plumbing technique is documented.

Yes, it is documented in "Pro Git" book's chapter [[https://git-scm.com/book/en/v2/Git-Internals-Git-Objects][10.2 Git Objects]]
under headline "Object Storage" at the end: 
"... there is a header stored with every object you commit to your Git object database."
"... Git first constructs a header which starts by identifying the type of object ... 
To that first part of the header, Git adds a space followed by the size in bytes of the content, 
and adding a final null byte".

